// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nonmuyozsxmucimmdggd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vbm11eW96c3htdWNpbW1kZ2dkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4NDA5NDEsImV4cCI6MjA1ODQxNjk0MX0.lmPoenU2x4N5vVfUDMjWQZmgq_2GbNU2_HkCX7jOelk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);